apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  annotations:
    ui.rancher/badge-color: "#0de326"
    ui.rancher/badge-icon-text: GPU
    ui.rancher/badge-text: nvidia
  name: cluster-gpu
  namespace: fleet-default
  labels:
    fleet-app-external-secrets: "true"
    fleet-app-cert-manager: "true"
    fleet-app-gpu-operator: "true"
    fleet-app-metallb: "true"
    fleet-app-external-dns: "true"
    fleet-app-longhorn: "true"
    fleet-app-suse-ai: "true"
    fleet-app-k3k: "true"
    fleet-app-local-path-provisioner: "true"
    fleet-app-neuvector: "true"
    fleet-app-jupyterhub: "true"
    fleet-app-rancher-monitoring: "true"
spec:
  kubernetesVersion: v1.32.4+rke2r1
  rkeConfig:
    etcd:
      snapshotRetention: 5
      snapshotScheduleCron: 0 */5 * * *
    machineGlobalConfig:
      cni: calico
      disable-kube-proxy: false
      etcd-expose-metrics: false
    machineSelectorConfig:
      - config:
          protect-kernel-defaults: false
    machineSelectorFiles:
      - fileSources:
          - secret:
              items:
                - key: secret-id
                  path: /var/lib/rancher/rke2/server/manifests/vault-secret-id.yaml
              name: vault-approle-secret-id
    registries:
      mirrors:
        docker.io:
          endpoint:
            - https://harbor.lan.ping6.nl
          rewrite:
            (.*): docker.io/$1
        dp.apps.rancher.io:
          endpoint:
            - https://harbor.lan.ping6.nl
          rewrite:
            (.*): dp.apps.rancher.io/$1
        gcr.io:
          endpoint:
            - https://harbor.lan.ping6.nl
          rewrite:
            (.*): gcr.io/$1
        ghcr.io:
          endpoint:
            - https://harbor.lan.ping6.nl
          rewrite:
            (.*): ghcr.io/$1
        k8s.gcr.io:
          endpoint:
            - https://harbor.lan.ping6.nl
          rewrite:
            (.*): k8s.gcr.io/$1
        quay.io:
          endpoint:
            - https://harbor.lan.ping6.nl
          rewrite:
            (.*): quay.io/$1
        registry.k8s.io:
          endpoint:
            - https://harbor.lan.ping6.nl
          rewrite:
            (.*): registry.k8s.io/$1
        registry.rancher.com:
          endpoint:
            - https://harbor.lan.ping6.nl
          rewrite:
            (.*): registry.rancher.com/$1
        registry.suse.com:
          endpoint:
            - https://harbor.lan.ping6.nl
          rewrite:
            (.*): registry.suse.com/$1
    upgradeStrategy:
      controlPlaneConcurrency: "1"
      controlPlaneDrainOptions:
        deleteEmptyDirData: true
        disableEviction: false
        enabled: false
        force: false
        gracePeriod: -1
        ignoreDaemonSets: true
        ignoreErrors: false
        postDrainHooks: null
        preDrainHooks: null
        skipWaitForDeleteTimeoutSeconds: 0
        timeout: 120
      workerConcurrency: "1"
      workerDrainOptions:
        deleteEmptyDirData: true
        disableEviction: false
        enabled: false
        force: false
        gracePeriod: -1
        ignoreDaemonSets: true
        ignoreErrors: false
        postDrainHooks: null
        preDrainHooks: null
        skipWaitForDeleteTimeoutSeconds: 0
        timeout: 120
