spec:
  valuesContent: |-
    controller:
      config:
        proxy-body-size: 128M
      publishService:
        enabled: true
      service:
        enabled: true
        loadBalancerIP: 192.168.96.60
