apiVersion: v1
kind: ConfigMap
metadata:
  name: gpsd-ui-config
  labels:
    app: gpsd-ui
data:
  GPSD_HOST: "radio-pi.lan.ping6.nl"
  GPSD_PORT: "2947"
  NTP_ENABLED: "true"
  NTP_HOST: "ntp.lan.ping6.nl"
  NTP_INTERVAL: "5"
  WEB_HOST: "0.0.0.0"
  WEB_PORT: "5000"
  LOG_LEVEL: "INFO"
