defaultNamespace: default

targetCustomizations:
  - name: demolab
    clusterSelector:
      matchLabels:
        management.cattle.io/cluster-display-name: demolab
    yaml:
      overlays:
        - demolab

overrideTargets:
  - clusterSelector:
      matchLabels:
        fleet-app-kube-ovn: "true"
