apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: label-gpu-nodes
spec:
  rules:
    - name: label-gpu-node
      labels:
        gpu: "on"
      matchAny:
        # Match 1: NVIDIA GPUs via Vendor ID
        - matchFeatures:
            - feature: pci.device
              matchExpressions:
                vendor: { op: In, value: ["10de"] }
        # Match 2: AMD GPUs via Vendor ID
        - matchFeatures:
            - feature: pci.device
              matchExpressions:
                vendor: { op: In, value: ["1002"] }
