driver:
  enabled: false
devicePlugin:
  config:
    name: time-slicing-config
    default: any
    create: true
    data:
      any: |-
        version: v1
        flags:
          migStrategy: none
        sharing:
          timeSlicing:
            resources:
            - name: nvidia.com/gpu
              replicas: 16
toolkit:
  env:
    - name: CONTAINERD_SOCKET
      value: /run/k3s/containerd/containerd.sock
dcgmExporter:
  serviceMonitor:
    enabled: true
    # interval: 15s
    # honorLabels: false
    # additionalLabels: {}
    # relabelings:
    #   - source_labels:
    #       - __meta_kubernetes_pod_node_name
    #     regex: (.*)
    #     target_label: instance
    #     replacement: $1
    #     action: replace
