apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: label-gpu-nodes
spec:
  rules:
    - name: label-gpu-node
      labels:
        gpu: "on"
      matchFeatures:
        - feature: rule.matched
          matchExpressions:
            nvidia.com/gpu.present: { op: IsTrue }
