apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rfc2136-keys
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: rfc2136-keys
  data:
    - secretKey: rfc2136-tsig-secret
      remoteRef:
        key: secretstore.lab.suse
        property: local-dns-tsig-secret
    - secretKey: rfc2136-tsig-keyname
      remoteRef:
        key: secretstore.lab.suse
        property: local-dns-key-name
