apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-secret
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: postgres-secret
  data:
    - secretKey: postgresPassword
      remoteRef:
        key: secretstore.lab.suse
        property: postgresql-superuser-password
    - secretKey: replicationPassword
      remoteRef:
        key: secretstore.lab.suse
        property: postgresql-replication-password
