apiVersion: v1
kind: Service
metadata:
  name: vault-0-external
  namespace: vault
spec:
  internalTrafficPolicy: Cluster
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: 8200
      protocol: TCP
      targetPort: 8200
  selector:
    statefulset.kubernetes.io/pod-name: vault-0
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: vault-1-external
  namespace: vault
spec:
  internalTrafficPolicy: Cluster
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: 8201
      protocol: TCP
      targetPort: 8200
  selector:
    statefulset.kubernetes.io/pod-name: vault-1
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: vault-2-external
  namespace: vault
spec:
  internalTrafficPolicy: Cluster
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: 8202
      protocol: TCP
      targetPort: 8200
  selector:
    statefulset.kubernetes.io/pod-name: vault-2
  type: LoadBalancer
