apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: n8n-claim0
  name: n8n-claim0
  namespace: n8n
spec:
  storageClass: local-path-nvme
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
