kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql-pv
  namespace: n8n
spec:
  storageClassName: local-path-nvme
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
