defaultNamespace: metallb-system
targetCustomizations:
  - name: demolab
    clusterSelector:
      matchLabels:
        management.cattle.io/cluster-display-name: demolab
    yaml:
      overlays:
        - demolab
  - name: cluster-test
    clusterSelector:
      matchLabels:
        management.cattle.io/cluster-display-name: cluster-test
    yaml:
      overlays:
        - cluster-test-2
overrideTargets:
  - clusterSelector:
      matchLabels:
        fleet-app-metallb: true
