apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cyclops-secrets
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: cyclops-secrets
  data:
    - secretKey: CYCLOPS_ADDR
      remoteRef:
        key: secretstore.lab.suse
        property: cyclops_addr
    - secretKey: CYCLOPS_DATABASE_HOST
      remoteRef:
        key: secretstore.lab.suse
        property: cyclops_db_host
    - secretKey: CYCLOPS_DATABASE_PORT
      remoteRef:
        key: secretstore.lab.suse
        property: cyclops_db_port
    - secretKey: CYCLOPS_DATABASE_NAME
      remoteRef:
        key: secretstore.lab.suse
        property: cyclops_db_name
    - secretKey: CYCLOPS_DATABASE_USER
      remoteRef:
        key: secretstore.lab.suse
        property: cyclops_db_user
    - secretKey: CYCLOPS_DATABASE_PASSWORD
      remoteRef:
        key: secretstore.lab.suse
        property: cyclops_db_password
    - secretKey: CYCLOPS_ADMIN_USER
      remoteRef:
        key: secretstore.lab.suse
        property: cyclops_admin_user
    - secretKey: CYCLOPS_ADMIN_PASS
      remoteRef:
        key: secretstore.lab.suse
        property: cyclops_admin_pass
    - secretKey: CYCLOPS_SESSION_KEY
      remoteRef:
        key: secretstore.lab.suse
        property: cyclops_session_key
