apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: git-p6lab-token
spec:
  refreshInterval: "300s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: git-p6lab-token
  data:
    - secretKey: token
      remoteRef:
        key: secretstore.lab.suse
        property: git-p6lab-repo-token
