apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nvidia-registry
spec:
  refreshInterval: "300s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: nvidia-registry
  data:
    - secretKey: user
      remoteRef:
        key: secretstore.lab.suse
        property: nvidia-registry-user
    - secretKey: token
      remoteRef:
        key: secretstore.lab.suse
        property: nvidia-registry-token
