apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aif-operator-rancher-catalog
spec:
  refreshInterval: "300s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: aif-operator-rancher-catalog
  data:
    - secretKey: ca.crt
      remoteRef:
        key: secretstore.lab.suse
        property: ca-crt
    - secretKey: token
      remoteRef:
        key: secretstore.lab.suse
        property: rancher-api-token
